Updated the readme .
aniruddha-adhikary/mrt-buddy pull request #27
Opened 2024-11-04 13:49 UTC by Nafisarkar

![Uploading Annotation 2024-11-04 195111.png…]()
Added a banner also update the readme with instruction . button for download and joining whatsapp

2024-11-04 16:11 UTC, aniruddha-adhikary requested changes
Thank you so much for choosing to contribute!

Overall looks great. I suppose the text is a bit Chat-GPT-esque. A little rewrite may be in order.

2024-11-04 16:11 UTC, aniruddha-adhikary commented on README.md
> +MRT Buddy is an unofficial community-driven Android app designed to check the balance of your Dhaka MRT Card.
Please explicitly mention the app is not affiliated with DMTCL, JICA, Government of Bangladesh or any of its affiliates!

2024-11-04 16:11 UTC, aniruddha-adhikary commented on README.md
> +Android App for Dhaka MRT Card Balance Check
Is there a more elegant way to say this?

2024-11-04 16:11 UTC, aniruddha-adhikary commented on README.md
> +* No API connectivity required, ensuring a seamless user experience
The transition from NO API to Seamlessness... doesn't really connect. Can we remove this line?

2024-11-04 16:11 UTC, aniruddha-adhikary commented on README.md
> +* Reads the last 10 transactions from the FeliCa NFC Card
What is FeliCa? I think we may need to mention the RapidPass / MRT Card is a FeliCa card.

2024-11-04 16:11 UTC, aniruddha-adhikary commented on README.md
> +* Place the MRT pass near the back of your phone properly for a successful scan.
Could we add a copyright-free graphic animation of how NFC placement should work? Or maybe a YouTube video?

2024-11-04 16:11 UTC, aniruddha-adhikary commented on README.md
> +[![Join WhatsApp Channel](https://shields.io/badge/Join-WhatsApp%20Channel-green?style=for-the-badge&logo=whatsapp&logoColor=white)](https://chat.whatsapp.com/KY8xK0qRm4t4l0q4qf4s)
one more `<br>`? :D

2024-11-04 16:31 UTC, Nafisarkar commented on README.md
> +MRT Buddy is an unofficial community-driven Android app designed to check the balance of your Dhaka MRT Card.
Sure

2024-11-04 16:33 UTC, Nafisarkar commented on README.md
> +Android App for Dhaka MRT Card Balance Check
i suppose 😐

2024-11-04 16:33 UTC, Nafisarkar commented on README.md
> +* No API connectivity required, ensuring a seamless user experience
Removed !

2024-11-04 16:34 UTC, Nafisarkar commented on README.md
> +* Reads the last 10 transactions from the FeliCa NFC Card
Fixed 👾

2024-11-04 16:35 UTC, Nafisarkar commented on README.md
> +[![Join WhatsApp Channel](https://shields.io/badge/Join-WhatsApp%20Channel-green?style=for-the-badge&logo=whatsapp&logoColor=white)](https://chat.whatsapp.com/KY8xK0qRm4t4l0q4qf4s)
Missed one . Destroyed ! 💥

2024-11-04 16:59 UTC, kazimmt commented on README.md
> +* Place the MRT pass near the back of your phone properly for a successful scan.
![MRT-Buddy-App-Usage](https://github.com/user-attachments/assets/70daf45c-f5d1-453a-be38-96ef369156e1)

2024-11-04 17:25 UTC, Nafisarkar commented on README.md
> +* Place the MRT pass near the back of your phone properly for a successful scan.
How about a gif ?

2024-11-05 12:02 UTC, aniruddha-adhikary commented
Amazing work @Nafisarkar. Thank you so much for taking the time to organize all of this. Appreciate!

2024-11-05 12:02 UTC, merged

2024-11-05 12:03 UTC, aniruddha-adhikary reviewed
Approved